#!/bin/bash
# BeyondAcademic 一键部署脚本 / One-Click Deployment Script
# 支持管道执行 / Supports piped execution: curl -fsSL <url> | sudo bash
#
# 环境变量配置 / Environment variable overrides:
#   DOMAIN          - 域名 (default: server IP)
#   INSTALL_DIR     - 安装目录 (default: /opt/beyondacademic)
#   CONFIGURE_SSL   - 配置SSL yes/no (default: no)
#   SSL_EMAIL       - SSL证书邮箱 (required if CONFIGURE_SSL=yes)
#   DB_PASSWORD     - 数据库密码 (auto-generated if unset)
#   SECRET_KEY      - 应用密钥 (auto-generated if unset)
#   HTTP_PORT       - HTTP端口 (default: 80)

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Root check ───────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  error "This script must be run as root. Use: sudo bash deploy.sh"
  exit 1
fi

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   BeyondAcademic  ·  Auto Deployment     ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Configuration (env overrides or safe defaults) ───────────────────────────
INSTALL_DIR="${INSTALL_DIR:-/opt/beyondacademic}"
HTTP_PORT="${HTTP_PORT:-80}"
CONFIGURE_SSL="${CONFIGURE_SSL:-no}"

# Detect public IP as fallback domain
detect_ip() {
  curl -s --max-time 5 https://api.ipify.org 2>/dev/null \
    || hostname -I | awk '{print $1}' \
    || echo "localhost"
}
DOMAIN="${DOMAIN:-$(detect_ip)}"

DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -hex 16)}"
SECRET_KEY="${SECRET_KEY:-$(openssl rand -hex 32)}"

info "Install directory : $INSTALL_DIR"
info "Domain / IP       : $DOMAIN"
info "HTTP port         : $HTTP_PORT"
info "SSL               : $CONFIGURE_SSL"
echo ""

# ── Step 1: System update ────────────────────────────────────────────────────
info "[1/9] Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq
success "System updated"

# ── Step 2: Install Docker ───────────────────────────────────────────────────
info "[2/9] Checking Docker..."
if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker --now
  success "Docker installed"
else
  success "Docker already installed ($(docker --version))"
fi

# ── Step 3: Install Docker Compose plugin ────────────────────────────────────
info "[3/9] Checking Docker Compose..."
if ! docker compose version &>/dev/null; then
  apt-get install -y -qq docker-compose-plugin
  success "Docker Compose installed"
else
  success "Docker Compose already installed"
fi

# ── Step 4: Clone / update repository ────────────────────────────────────────
info "[4/9] Fetching application source..."
if [[ ! -d "$INSTALL_DIR/.git" ]]; then
  mkdir -p "$INSTALL_DIR"
  git clone --depth 1 https://github.com/wangdajin062/BeyondAcademic.git "$INSTALL_DIR"
  success "Repository cloned to $INSTALL_DIR"
else
  git -C "$INSTALL_DIR" pull --ff-only
  success "Repository updated"
fi
cd "$INSTALL_DIR"

# ── Step 5: Environment file ─────────────────────────────────────────────────
info "[5/9] Configuring environment..."
if [[ "$CONFIGURE_SSL" == "yes" ]]; then
  ALLOWED_ORIGINS="https://${DOMAIN},https://www.${DOMAIN}"
else
  ALLOWED_ORIGINS="http://${DOMAIN},http://localhost"
fi

cat > .env <<EOF
# Auto-generated by deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DB_PASSWORD=${DB_PASSWORD}
SECRET_KEY=${SECRET_KEY}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ENVIRONMENT=production
HTTP_PORT=${HTTP_PORT}
EOF
success "Environment file written"

# ── Step 6: Create required directories ──────────────────────────────────────
info "[6/9] Preparing directories..."
mkdir -p certbot/conf certbot/www backend/logs
chmod 755 backend/logs
success "Directories ready"

# ── Step 7: Build and start core services ────────────────────────────────────
info "[7/9] Building and starting services (this may take a few minutes)..."

if [[ "$CONFIGURE_SSL" == "yes" ]]; then
  COMPOSE_FILE="docker-compose.prod.yml"

  # Patch domain into nginx prod conf
  sed -i "s/yourdomain\.com/${DOMAIN}/g" nginx/conf.d/beyondacademic.conf

  docker compose -f "$COMPOSE_FILE" pull --quiet db redis 2>/dev/null || true
  docker compose -f "$COMPOSE_FILE" up -d --build db redis backend frontend

  info "Waiting for backend to be ready..."
  timeout 120 bash -c 'until docker compose -f docker-compose.prod.yml exec -T backend curl -sf http://localhost:8000/health; do sleep 3; done' \
    || warn "Backend health check timed out — check logs if issues persist"

  # Obtain SSL cert before starting nginx with HTTPS config
  if [[ -n "${SSL_EMAIL:-}" ]]; then
    docker compose -f "$COMPOSE_FILE" run --rm certbot certonly --webroot \
      --webroot-path=/var/www/certbot \
      --email "$SSL_EMAIL" --agree-tos --no-eff-email \
      -d "$DOMAIN" -d "www.${DOMAIN}" \
      && success "SSL certificate obtained" \
      || warn "SSL certificate failed — nginx will start without HTTPS"
  else
    warn "SSL_EMAIL not set — skipping certificate issuance"
  fi

  docker compose -f "$COMPOSE_FILE" up -d --build
else
  COMPOSE_FILE="docker-compose.yml"
  docker compose -f "$COMPOSE_FILE" pull --quiet db redis 2>/dev/null || true
  docker compose -f "$COMPOSE_FILE" up -d --build

  info "Waiting for backend to be ready..."
  timeout 120 bash -c 'until docker compose exec -T backend curl -sf http://localhost:8000/health; do sleep 3; done' \
    || warn "Backend health check timed out — check logs if issues persist"
fi

success "All services started"

# ── Step 8: Health verification ───────────────────────────────────────────────
info "[8/9] Verifying deployment..."
sleep 5
HEALTH=$(curl -sf "http://localhost:${HTTP_PORT}/health" 2>/dev/null || echo "unreachable")
if echo "$HEALTH" | grep -q "healthy"; then
  success "Health check passed: $HEALTH"
else
  warn "Health check returned: $HEALTH"
  warn "Check logs: docker compose -f $INSTALL_DIR/$COMPOSE_FILE logs -f"
fi

# ── Step 9: Summary ───────────────────────────────────────────────────────────
info "[9/9] Deployment complete!"
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   BeyondAcademic is running!                         ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
if [[ "$CONFIGURE_SSL" == "yes" ]]; then
  echo "  App:      https://${DOMAIN}"
  echo "  API docs: https://${DOMAIN}/docs"
else
  echo "  App:      http://${DOMAIN}:${HTTP_PORT}"
  echo "  API docs: http://${DOMAIN}:${HTTP_PORT}/docs"
fi
echo ""
echo "  Install dir: $INSTALL_DIR"
echo ""
echo "Useful commands:"
echo "  View logs:     docker compose -f $INSTALL_DIR/$COMPOSE_FILE logs -f"
echo "  Stop:          docker compose -f $INSTALL_DIR/$COMPOSE_FILE down"
echo "  Restart:       docker compose -f $INSTALL_DIR/$COMPOSE_FILE restart"
echo "  Update:        git -C $INSTALL_DIR pull && docker compose -f $INSTALL_DIR/$COMPOSE_FILE up -d --build"
echo ""
echo -e "${YELLOW}Demo login: tester / test123456${NC}"
echo ""
